version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - EXPERIMENT_CONFIG_PATH=/app/config/experiment.json
      - EXPERIMENT_DATABASE_URL=sqlite:///./data/experiment.db
      - EXPERIMENT_IP_HASH_SECRET=dev-secret
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      - VITE_API_BASE=http://backend:8000
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
